language: cpp
compiler: g++
dist: xenial

script:
- git ls-files src/!*.txt | xargs clang-format -i && git diff --exit-code
- cd tests
- ./install.sh
- ./Gtests.exe
- cd ..
- cmake CMakeLists.txt 
- make
